### ISSUE TITLE
Tagged tar ball missing dependencies

### ISSUE THREAD

**Issue by eFAILution** [defenseunicorns/doc-site-template#12]
**Problem Statement:** 

After downloading the v1.0.0 tar ball the `npm ci` command will not run as husky requires the .git directory.
```
> husky install && npm run update

husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
npm ERR! code 1
npm ERR! path doc-site-template
npm ERR! command failed
npm ERR! command sh -c husky install && npm run update
```

**Acceptance Criteria:** 
 
Include .git or some other workaround that will ensure tagged tar balls have full functionality.

**Comment by bdfinst** [comment]
Removed pre-commit hooks.
