### ISSUE TITLE
How can I use this template and have version pinning?

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/doc-site-template#47]
**Problem Statement:** 

https://docs.pepr.dev has a Releases dropdown and updates given that selection. There may be additional changes to the template implemented https://github.com/defenseunicorns/pepr-docs

I'd like to see documentation on how to effectively leverage this template and replicate that need.

**Acceptance Criteria:** 
 
Documenation added and tested that would allow me to create a new docs site and have version pinning.

**Comment by devinallen-07** [comment]
Here is the repo for the templates: https://github.com/defenseunicorns/doc-site-template
Andrew would LOVE to see this get worked but not to disrupt work....But would LOVE to see it done...

**Comment by bdfinst** [comment]
I'll update the template README for some common links, but the documentation for this exists on the theme doc site.
https://main--starlit-valkyrie-7f1dd9.netlify.app/docs/adding-content/versioning/
